---
title: AndrewN.co
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Andrew.Nicolalde.2016@live.rhul.ac.uk
description: First year Computer Science student at Royal Holloway, University of
  London
baseurl: ''
url: ''
twitter_username: andnicolalde
github_username: andrewnicolalde
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
